# ===============================================================
# modernbert_ner_trainer.py
# Optimised for ModernBERT Token Classification (NER)
#
# Requirements:
# pip install torch transformers datasets evaluate scikit-learn seqeval
# ===============================================================

import json
import torch
import numpy as np
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
import evaluate

# --- CONFIGURATION ---
MODEL_ID = "answerdotai/ModernBERT-base"
DATA_DIR = "./modernbert_data"
OUTPUT_DIR = "./modernbert_ner_model"

MAX_LENGTH = 128
BATCH_SIZE = 32
LEARNING_RATE = 2e-5
NUM_EPOCHS = 4

def load_label_maps():
    """Load the label mappings generated by the NER dataset script."""
    with open(f"{DATA_DIR}/ner_label_map.json", "r") as f:
        maps = json.load(f)
    
    label2id = maps["label2id"]
    # Ensure keys are integers for id2label
    id2label = {int(k): v for k, v in maps["id2label"].items()}
    
    # Create an ordered list of string labels
    label_list = [id2label[i] for i in range(len(id2label))]
    
    return label2id, id2label, label_list

def main():
    print("Initialising ModernBERT NER Training Pipeline")
    
    label2id, id2label, label_list = load_label_maps()
    num_labels = len(label_list)
    
    print(f"Loading datasets from {DATA_DIR}...")
    dataset = load_dataset(
        "json",
        data_files={
            "train": f"{DATA_DIR}/ner_train.jsonl",
            "validation": f"{DATA_DIR}/ner_validation.jsonl",
            "strict_test": f"{DATA_DIR}/ner_strict_validation.jsonl"
        }
    )
    
    print(f"Loading tokenizer {MODEL_ID}...")
    # add_prefix_space is sometimes required for Roberta/ModernBERT tokenizers in NER
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, add_prefix_space=True)
    
    def tokenize_and_align_labels(examples):
        """
        Realigns the BIO tags with the newly generated sub-word tokens.
        Assigns -100 to special tokens and trailing sub-words so PyTorch ignores them in the loss calculation.
        """
        tokenized_inputs = tokenizer(
            examples["tokens"], 
            truncation=True, 
            max_length=MAX_LENGTH,
            is_split_into_words=True
        )

        labels = []
        for i, label in enumerate(examples["ner_tags"]):
            word_ids = tokenized_inputs.word_ids(batch_index=i)
            previous_word_idx = None
            label_ids = []
            for word_idx in word_ids:
                # Special tokens have a word id that is None. We set the label to -100 so they are automatically
                # ignored in the loss function.
                if word_idx is None:
                    label_ids.append(-100)
                # We set the label for the first token of each word.
                elif word_idx != previous_word_idx:
                    label_ids.append(label[word_idx])
                # For the other tokens in a word, we set the label to -100 so they are ignored.
                else:
                    label_ids.append(-100)
                previous_word_idx = word_idx

            labels.append(label_ids)

        tokenized_inputs["labels"] = labels
        return tokenized_inputs

    print("Tokenizing and aligning dataset...")
    tokenized_datasets = dataset.map(
        tokenize_and_align_labels,
        batched=True,
        remove_columns=["tokens", "ner_tags"] # Remove original unaligned columns
    )
    
    print(f"Loading model {MODEL_ID}...")
    model = AutoModelForTokenClassification.from_pretrained(
        MODEL_ID,
        num_labels=num_labels,
        id2label=id2label,
        label2id=label2id
    )
    
    # This collator automatically pads both the inputs AND the labels (padding labels with -100)
    data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)
    
    # Load the standard evaluation metric for NER
    seqeval = evaluate.load("seqeval")

    def compute_metrics(p):
        """Calculates Precision, Recall, F1, and Accuracy for the NER tags."""
        predictions, labels = p
        predictions = np.argmax(predictions, axis=2)

        # Remove the -100 tags and convert predicted IDs back to string labels
        true_predictions = [
            [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
            for prediction, label in zip(predictions, labels)
        ]
        true_labels = [
            [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
            for prediction, label in zip(predictions, labels)
        ]

        results = seqeval.compute(predictions=true_predictions, references=true_labels)
        if results is None:
            return {
                "precision": 0.0,
                "recall": 0.0,
                "f1": 0.0,
                "accuracy": 0.0,
            }
        return {
            "precision": results["overall_precision"],
            "recall": results["overall_recall"],
            "f1": results["overall_f1"],
            "accuracy": results["overall_accuracy"],
        }
    
    training_args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        learning_rate=LEARNING_RATE,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=NUM_EPOCHS,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        push_to_hub=False,
        fp16=torch.cuda.is_available(), 
        logging_dir="./logs",
        logging_steps=50,
    )
    
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets["validation"], # Standard validation for epoch tuning
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )
    
    print("Starting NER training process...")
    trainer.train()
    
    print("Training complete. Commencing strict holdout evaluation...")
    strict_results = trainer.evaluate(tokenized_datasets["strict_test"])  # type: ignore
    
    print("\nFinal Strict Test Results:")
    for key, value in strict_results.items():
        print(f"  {key}: {value:.4f}")
    
    print(f"\nSaving final model to {OUTPUT_DIR}...")
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    
    print("NER Pipeline finished successfully.")

if __name__ == "__main__":
    main()