#!/usr/bin/env python3
"""
One-shot template replacement for modernbert-intent.py
Applies all feedback fixes: 50+ templates per intent, bare QUERY_TASK templates,
{past_complete} fix in COMPLETE_TASK, removed availability templates from QUERY_EVENT,
added them to FIND_FREE_TIME, plus new patterns for all intents.
"""
import json

FILE_PATH = '/Users/danish/Desktop/PROJECT/src/ai/modernbert-intent.py'


def replace_template_list(content, intent_name, new_templates):
    start_marker = f'    "{intent_name}": [\n'
    end_marker = '\n    ],'
    start_idx = content.find(start_marker)
    if start_idx == -1:
        print(f"  ERROR: Could not find start for {intent_name}")
        return content
    search_from = start_idx + len(start_marker)
    end_idx = content.find(end_marker, search_from)
    if end_idx == -1:
        print(f"  ERROR: Could not find end for {intent_name}")
        return content
    new_items = '\n'.join(f'        {json.dumps(t)},' for t in new_templates)
    new_content = (content[:start_idx] + start_marker + new_items +
                   end_marker + content[end_idx + len(end_marker):])
    print(f"  Replaced {intent_name}: {len(new_templates)} templates")
    return new_content


# ── CREATE_EVENT (67 templates) ───────────────────────────────────────────────
CREATE_EVENT = [
    # Standard scheduling commands
    "{polite} {schedule} a {event} with {person} at {time}",
    "{polite} {schedule} a {event} for {time}",
    "I need to {schedule} a {event} in {location}",
    "I'd like to {schedule} a {event} with {person}",
    "Can we {schedule} a {event} for {duration}?",
    "Let's {schedule} a {event} {time}",
    "We should {schedule} a {event} with {person}",
    "I want to {schedule} a {event} at {time}",
    "Need to {schedule} a {event} {time}",
    "Time to {schedule} a {event} with {person}",
    "{schedule} {event} with {person} {time}",
    "{schedule} {event} {time}",
    "Book {event} {location} {time}",
    "New {event} with {person}",
    "{event} with {person} at {time}",
    "{event} {time} {location}",
    "Add {event} to calendar {time}",
    "I have a {event} at {time}",
    "Put {event} in diary {time}",
    "Pencil in {event} {time}",
    "Slot in {event} with {person}",
    "Get a {event} in the diary for {time}",
    "Lock in a {event} with {person}",
    "Sort out a {event} for {time}",
    "Fix up a {event} in {location}",
    "Pop a {event} in for {time}",
    "Chuck a {event} in the calendar {time}",
    "Stick a {event} in for {time}",
    "Whack a {event} in the diary {time}",
    "Can you {schedule} a {event} for me {time}?",
    "Could we set up a {event} {time}?",
    "Organise a {event} with {person} for {time}",
    "Arrange a {event} with {person} at {time}",
    "Plan a {event} for {time}",
    "Get a {event} in the books for {time}",
    "Create a new {event} for {time}",
    "Set up a new {event} with {person}",
    "I need a {event} in the diary for {time}",
    "Please add a {event} on {time}",
    "Set up a {event} at {location} for {time}",
    "Add a {event} in {location} for {time}",
    "Log a {event} for {time}",
    "Note down a {event} for {time}",
    # All-day and busy blocks
    "Block out {time} all day",
    "Mark {time} as busy",
    "Block {time} in my calendar",
    "Block out {duration} for a {event} {time}",
    "Put aside {time} for a {event}",
    "Reserve {time} for a {event}",
    "Hold {time} for a {event}",
    "Set me as unavailable {time}",
    "Put me as unavailable {time}",
    # Away / travel / OOO
    "I'm away {time}",
    "I'm away on {time}",
    "I'll be travelling {time}",
    "I'm out of office {time}",
    "Set me as out of office {time}",
    "Mark me as out of office {time}",
    "I'll be off {time}",
    "Put me down as away {time}",
    # Implicit / declarative creation
    "I've got a {event} on {time}",
    "I've got a {event} at {time}",
    "There's a {event} at {time}",
    "I've got {person} coming over {time}",
    "I'm meeting {person} at {time}",
    "I've arranged a {event} with {person} for {time}",
    "There's a {event} with {person} at {location}",
]

# ── UPDATE_EVENT (69 templates) ───────────────────────────────────────────────
UPDATE_EVENT = [
    # Rescheduling / time changes
    "{polite} {reschedule} the {event} to {time}",
    "{polite} change the {event} to {time}",
    "I need to {reschedule} my {event} to {time}",
    "Can we {reschedule} the {event} to {time}?",
    "The {event} needs to be moved to {time}",
    "I want to {reschedule} the {event} to {time}",
    "We need to {reschedule} the {event} with {person}",
    "Could you {reschedule} my {time} {event}?",
    "I'd like to {reschedule} the {event} to {time}",
    "{reschedule} {event} to {time}",
    "Move {event} to {time}",
    "Change {event} time to {time}",
    "Shift {event} to {time}",
    "Push {event} back by {duration}",
    "Bring {event} forward to {time}",
    "Bump {event} to {time}",
    "{event} now at {time}",
    "Can we do {time} instead for the {event}?",
    "Let's make it {time} for the {event}",
    "Slide the {event} to {time}",
    "Shunt the {event} to {time} instead",
    "The {event} is moving to {time}",
    "I'm running late, move the {event} to {time}",
    "Delay the {event} by {duration}",
    "Push the {event} to {time}",
    "Move the {event} earlier to {time}",
    "Move the {event} later to {time}",
    "Change the {event} to start at {time} instead",
    "Start the {event} at {time} instead",
    "Move the {event} an hour later",
    # Location changes
    "Update {event} location to {location}",
    "Change the location of the {event} to {location}",
    "Move the {event} from {location} to online",
    "Switch the {event} to {location}",
    "Switch the {event} from in-person to online",
    "Change the venue of the {event} to {location}",
    "Move the {event} to {location}",
    "The {event} is now at {location}",
    "Update the {event} to be at {location}",
    "Change {event} to {location}",
    "Move the {event} online",
    # Duration changes
    "Make the {event} {duration} longer",
    "Shorten the {event} to {duration}",
    "Extend the {event} by {duration}",
    "Change the duration of the {event} to {duration}",
    "Cut the {event} down to {duration}",
    "Give the {event} an extra {duration}",
    "Make the {event} shorter",
    "The {event} should only be {duration}",
    # Attendee changes
    "Add {person} to the {event}",
    "Can you add {person} to the {event}?",
    "Invite {person} to the {event}",
    "Include {person} in the {event}",
    "Please add {person} to the {event} invite",
    "Add {person} as an attendee on the {event}",
    "Remove {person} from the {event}",
    "Drop {person} from the {event}",
    "Take {person} off the {event}",
    "Uninvite {person} from the {event}",
    "Can you remove {person} from the {event}?",
    # Title / name changes
    "Rename the {event} to {task}",
    "Change the title of the {event} to {task}",
    "Update the name of the {event} to {task}",
    "Retitle the {event} as {task}",
    # Description / notes
    "Update the description of the {event}",
    "Add a note to the {event}",
    "Add some notes to the {event}",
    "Update the {event} details",
    "Change the agenda for the {event}",
]

# ── DELETE_EVENT (52 templates) ───────────────────────────────────────────────
DELETE_EVENT = [
    "{polite} {cancel} the {event}",
    "{polite} {cancel} my {event} with {person}",
    "I need to {cancel} the {event} {time}",
    "Can you {cancel} the {event} for me?",
    "I want to {cancel} my {time} {event}",
    "The {event} needs to be cancelled",
    "I'd like to {cancel} the {event} with {person}",
    "We need to {cancel} the {event} {time}",
    "{cancel} {event} {time}",
    "{cancel} the {time} {event}",
    "Remove {event} from calendar",
    "Delete {event} with {person}",
    "Drop the {event} {time}",
    "Scrap the {event} with {person}",
    "Bin the {event} {time}",
    "Nix the {event} with {person}",
    "The {event} {time} is off",
    "Forget about the {event} with {person}",
    "Kill the {event} on {time}",
    "Ditch the {event} {time}",
    "Pull the plug on the {event}",
    "Cancel the {event} {time} because I'm ill",
    "I can't make the {event}, cancel it",
    "{cancel} the {event} as I'm double-booked",
    "Something came up, {cancel} the {event}",
    "I'm not feeling well, {cancel} the {event}",
    "Can we {cancel} the {event} {time}?",
    "Could you remove the {event} from my diary?",
    "Take the {event} off my schedule",
    "Clear the {event} from my calendar",
    "I need to cancel the {event} with {person}",
    "The {event} is no longer happening",
    "Please remove the {event} from my diary",
    "Erase the {event} from my calendar",
    "Wipe the {event} from my schedule",
    "Get rid of the {event}",
    "I won't be attending the {event}, please remove it",
    "I want to withdraw from the {event}",
    "Please call off the {event} with {person}",
    "The {event} has been cancelled, update my diary",
    "I'm pulling out of the {event}",
    "I need to pull out of the {event} at {time}",
    "Can we call off the {event}?",
    "Please cancel the {event} invitation",
    "Scrub the {event} from my calendar",
    "The {event} is off, please update my diary",
    "I want to uninvite myself from the {event}",
    "Remove the {event} completely",
    "The {event} is cancelled",
    "I've decided to cancel the {event}",
    "Please remove all {event} entries",
    "Take the {event} off",
]

# ── QUERY_EVENT (65 templates) ────────────────────────────────────────────────
QUERY_EVENT = [
    # Bare / no-slot templates
    "What have I got today?",
    "What's on today?",
    "What's my schedule?",
    "What's my agenda today?",
    "Show me my calendar",
    "What's my diary looking like?",
    "What meetings have I got?",
    "What's coming up in my calendar?",
    "What's happening today?",
    "What events have I got?",
    "Show me my schedule",
    "Any meetings today?",
    "What's on my calendar?",
    "What events are coming up?",
    "What have I got in my diary?",
    "What's my agenda?",
    "What am I doing today?",
    "What's in my calendar?",
    "What's my day looking like?",
    "What's my week looking like?",
    # Templates with {time}
    "What's on my calendar {time}?",
    "What events do I have {time}?",
    "What am I doing {time}?",
    "Do I have anything scheduled {time}?",
    "What's happening {time}?",
    "Can you show me my calendar for {time}?",
    "I want to see my schedule for {time}",
    "What does my diary look like {time}?",
    "Have I got anything on {time}?",
    "What's my agenda for {time}?",
    "How many meetings do I have {time}?",
    "Is there anything in my calendar {time}?",
    "Pull up my diary for {time}",
    "Check my schedule for {time}",
    "What've I got on {time}?",
    "Show calendar {time}",
    "Check schedule {time}",
    "List events {time}",
    "What's scheduled {time}?",
    "My diary {time}",
    "Any events {time}?",
    "What's my schedule for {time}?",
    "What's happening in my calendar {time}?",
    "What've I got in my diary {time}?",
    # Templates with {event}
    "When is my {event}?",
    "Where is the {event}?",
    "Who is attending the {event}?",
    "How long is the {event}?",
    "What time does the {event} start?",
    "Where's the {event} happening?",
    "Who's coming to the {event}?",
    "When's my next {event}?",
    "What time is my {event}?",
    "Is my {event} still on?",
    "Do I have any {event} {time}?",
    "When does my {event} end?",
    "Where's the {event} taking place?",
    # Templates with {person}
    "Have I got anything with {person}?",
    "When am I meeting {person}?",
    "When am I next seeing {person}?",
    "What have I got with {person}?",
    "Do I have anything scheduled with {person}?",
    "Is there anything with {person} {time}?",
    "When's my {event} with {person}?",
]

# ── FIND_FREE_TIME (62 templates) ─────────────────────────────────────────────
FIND_FREE_TIME = [
    # Basic availability queries
    "When am I free {time}?",
    "Find me a free slot {time}",
    "What times are available {time}?",
    "I need to find some free time {time}",
    "Can you find a gap in my calendar {time}?",
    "Where do I have availability {time}?",
    "I'm looking for a free {duration} slot",
    "Find me an opening {time}",
    "Find free time {time}",
    "Check availability {time}",
    "Free slots {time}",
    "Gaps in calendar {time}",
    "Available times {time}",
    "Open slots {time}",
    "When free {time}?",
    # Duration / event-size focused
    "Find a time for a {duration} {event}",
    "I need a {duration} slot for a {event}",
    "Find a gap for a {event}",
    "When can I fit in a {event}?",
    "Where can I squeeze in a {event}?",
    "Find me a {duration} window {time}",
    "What free windows do I have {time}?",
    "Is there a {duration} gap {time}?",
    "Find the next available {duration} slot",
    "When's my next free {duration}?",
    "Look for a gap of at least {duration} in my calendar",
    "Where can I find {duration} of free time {time}?",
    "Any free {duration} blocks {time}?",
    # Diary / schedule gaps
    "Do I have any free time {time}?",
    "Is there space in my diary {time}?",
    "Any gaps {time}?",
    "What's my earliest free slot {time}?",
    "When's my next free hour {time}?",
    "Have I got any openings {time}?",
    "Show me the gaps in my diary {time}",
    "What does my free time look like {time}?",
    "Give me a list of free slots for {time}",
    "Show all available windows {time}",
    "Find me breathing room in my calendar {time}",
    "Where am I not booked {time}?",
    "Am I busy all day {time}?",
    # Clash / conflict / availability checks (moved from QUERY_EVENT)
    "Am I free at {time}?",
    "Do I have any clashes at {time}?",
    "Is {time} free for me?",
    "Am I available at {time}?",
    "Is my calendar clear at {time}?",
    "Any conflicts at {time}?",
    "Is {time} blocked out?",
    "Do I have any commitments at {time}?",
    "Is {time} open for me?",
    "Have I got space at {time}?",
    "Am I double-booked at {time}?",
    # Mutual / group availability
    "Find a time when {person} is free",
    "When are {person} and I both available?",
    "Check mutual availability with {person}",
    "When is {person} free {time}?",
    "Find a slot when {person} and I are both free",
    "When can {person} and I meet?",
    "Are {person} and I free at the same time {time}?",
    "Find a {duration} window where {person} and I are both available",
    "What times work for both {person} and me {time}?",
]

# ── SUGGEST_TIME (52 templates) ───────────────────────────────────────────────
SUGGEST_TIME = [
    "{polite} suggest a time for the {event}",
    "When should I schedule the {event}?",
    "Can you recommend a time for the {event}?",
    "What's a good time for the {event}?",
    "Propose some times for the {event}",
    "What time would work best for a {event}?",
    "I need suggestions for when to have the {event}",
    "Can you pick a time for the {event}?",
    "Suggest time for {event}",
    "Recommend slot for {event}",
    "Best time for {event}?",
    "Optimal time for {event}",
    "When best for {event}?",
    "Propose times for {event}",
    "Suggest a {duration} window for a {event}",
    "What's the best time for a {duration} {event}?",
    "When's ideal for a {event} in {location}?",
    "Suggest a time that works for {person}",
    "What times work for the {event}?",
    "When would be good for the {event}?",
    "What do you suggest for the {event}?",
    "Any recommendations for the {event} time?",
    "What's optimal for the {event}?",
    "Throw out some times for the {event}",
    "Give me some options for the {event}",
    "Chuck some times at me for the {event}",
    "What times look good for the {event}?",
    "Suggest a few options for the {event}",
    "When works for {person} and the {event}?",
    "Pick a suitable time for the {event}",
    "What time would you recommend for the {event}?",
    "Help me pick a time for the {event}",
    "When would be the best time for the {event}?",
    "Suggest an optimal slot for the {event} with {person}",
    "Can you find a good time for a {duration} {event}?",
    "What's the ideal time for a {event} in {location}?",
    "Give me your best suggestion for the {event} time",
    "What time slots do you recommend for the {event}?",
    "Which time works best for the {event}?",
    "Tell me when to schedule the {event}",
    "I need you to pick the best time for the {event}",
    "Suggest times for the {event} with {person}",
    "What time would you book for the {event}?",
    "Advise me on when to hold the {event}",
    "Help me decide when to have the {event}",
    "I need a recommendation for the {event} timing",
    "When's the best window for a {event}?",
    "What's the optimal slot for the {event}?",
    "Can you advise on the best time for the {event}?",
    "Give me options for when to schedule the {event}",
    "What window do you suggest for the {event}?",
    "When do you think I should schedule the {event}?",
]

# ── CHANGE_RECURRENCE (67 templates) ─────────────────────────────────────────
CHANGE_RECURRENCE = [
    # Set up recurrence
    "Make this {event} repeat {recurrence}",
    "Change the recurrence of the {event} to {recurrence}",
    "Set the {event} to repeat {recurrence}",
    "I want this {event} to happen {recurrence}",
    "Can you make the {event} recurring {recurrence}?",
    "The {event} should repeat {recurrence}",
    "Turn the {event} into a recurring event {recurrence}",
    "I need the {event} to repeat {recurrence}",
    "Make {event} {recurrence}",
    "Set {event} to {recurrence}",
    "{event} should be {recurrence}",
    "Repeat {event} {recurrence}",
    "Recurring {event} {recurrence}",
    "{recurrence} for the {event}",
    # End / remove recurrence
    "Stop repeating the {event}",
    "Cancel the recurring {event}",
    "End the {event} series",
    "Make the {event} one-off",
    "Remove recurrence from {event}",
    "Stop the {event} from repeating",
    "Turn off the repeat for the {event}",
    "I no longer want the {event} to recur",
    "Set the {event} to stop repeating after {time}",
    "Convert the {event} back to a one-off",
    # Change recurrence pattern
    "Change the {event} from weekly to {recurrence}",
    "Update the {event} recurrence to {recurrence}",
    "Switch the {event} to {recurrence}",
    "Alter the {event} repeat pattern to {recurrence}",
    "Can the {event} repeat {recurrence}?",
    "Make the {event} a {recurrence} thing",
    "Would it be possible to repeat the {event} {recurrence}?",
    "Let's do this {event} {recurrence}",
    "Make it a regular {event} {recurrence}",
    "Put this {event} on repeat {recurrence}",
    "Change how often the {event} repeats",
    "Update the frequency of the {event} to {recurrence}",
    "Adjust the {event} to repeat {recurrence}",
    "Move the {event} to a {recurrence} schedule",
    "I'd like the {event} to occur {recurrence}",
    "Can we change the {event} to happen {recurrence}?",
    "Set up a {recurrence} {event}",
    "I want to make this {event} a standing {recurrence} one",
    "Let's schedule the {event} {recurrence}",
    "Please make the {event} repeat {recurrence}",
    "Add recurrence to the {event}",
    "The {event} should now happen {recurrence}",
    "Convert the one-off {event} to a recurring one",
    # One-off skip patterns
    "Skip this week's {event}",
    "Just cancel this one {event}, not the series",
    "Only cancel this occurrence of {event}",
    "Skip the next {event}",
    "Don't count this {event} as part of the series",
    "Pause the recurring {event} for {time}",
    "Miss this week's {event} but keep the rest going",
    "Skip just this instance of {event}",
    "Remove this single {event} from the series",
    "Keep the series but drop this particular {event}",
    "I'd like to skip tomorrow's {event}",
    "Exclude this occurrence of {event} from the series",
    "Cancel this week's {event} only",
    "Don't hold the {event} this time, but keep the series",
    "Skip this one {event} but leave the recurring schedule in place",
    "Temporarily skip the {event} this {time}",
    "Drop just this one instance of {event}",
]

# ── CREATE_TASK (77 templates) ────────────────────────────────────────────────
CREATE_TASK = [
    "{polite} add a task to {task}",
    "I need to add a task: {task}",
    "Create a task to {task}",
    "Add {task} to my to-do list",
    "I have a task to {task}",
    "Put {task} on my list",
    "I need to remember to {task}",
    "Can you create a task for me to {task}?",
    "Add task: {task}",
    "New task: {task}",
    "Task: {task}",
    "To-do: {task}",
    "Remember to {task}",
    "Don't forget to {task}",
    "Need to {task}",
    "Must {task}",
    "Got to {task}",
    "Add a task to {task} by {time}",
    "Create a task to {task} for {time}",
    "I need to {task} by {time}",
    "{task} deadline {time}",
    "{task} due {time}",
    "Task: {task} - due {time}",
    "Can you add {task} to my tasks?",
    "Would you create a task to {task}?",
    "Chuck {task} on my to-do list",
    "Stick {task} on my list",
    "Pop {task} in my tasks",
    "Whack {task} on the list",
    "Log a task to {task}",
    "Make a note to {task}",
    "Note down that I need to {task}",
    "Can you note that I need to {task}?",
    "Jot down to {task}",
    "Jot down: {task}",
    "Jot it down: {task}",
    "Note: {task}",
    "Can you jot down that I need to {task}?",
    "I need to make a note to {task}",
    "{polite} note down that I need to {task}",
    "Remind myself to {task}",
    "I should {task}",
    "I ought to {task}",
    "I need to get round to {task}",
    "I've got to {task}",
    "I must get round to {task}",
    "I've got {task} to do",
    "I need to get {task} done",
    "Schedule a task to {task}",
    "Create a new task: {task}",
    "Add a new task: {task}",
    "Set a task to {task}",
    "Make a to-do for {task}",
    "Queue up a task to {task}",
    "Add {task} to my task list",
    "Add {task} as a task",
    "Add an item to my to-do list: {task}",
    "Create to-do: {task}",
    "New to-do: {task}",
    "New item: {task}",
    "Log that I need to {task}",
    "Track that I need to {task}",
    "Put a task in for {task}",
    "Log a to-do: {task}",
    "Flag that I need to {task}",
    "I need to sort out {task}",
    "{polite} create a task to {task}",
    "Please add a task: {task}",
    "Could you add a task to {task}?",
    "I want to {task} by {time}",
    "Task for {time}: {task}",
    "Bung {task} on my list",
    "Add {task} to my task backlog",
    "I've been meaning to {task}",
    "I still need to {task}",
    "Put {task} on my radar",
]

# ── UPDATE_TASK (52 templates) ────────────────────────────────────────────────
UPDATE_TASK = [
    "{polite} {update} the task {task}",
    "I need to {update} my task {task}",
    "Can you {update} the {task} deadline to {time}?",
    "Change the task {task} deadline",
    "The task {task} needs to be updated",
    "I want to {update} my to-do {task}",
    "Could you {update} the task {task} details?",
    "Modify the task description to {task}",
    "{update} task: {task}",
    "Change task {task} to {time}",
    "Edit task: {task}",
    "Modify {task} deadline to {time}",
    "Task {task} deadline now {time}",
    "Push task {task} to {time}",
    "Move {task} deadline to {time}",
    "Change the {task} deadline to {time}",
    "Extend the {task} deadline to {time}",
    "Move the {task} due date to {time}",
    "Push the {task} deadline back to {time}",
    "Bring the {task} deadline forward to {time}",
    "Make the task {task} high priority",
    "Lower the priority of {task}",
    "Mark the task {task} as urgent",
    "Change {task} priority",
    "Can I change the task {task}?",
    "Could you update the {task} due date?",
    "Is it possible to extend the {task} deadline?",
    "Tweak the task {task} a bit",
    "Adjust the {task} deadline",
    "Shift the task {task} to {time}",
    "I need to change the task {task}",
    "Please update my task to {task}",
    "Update the {task} task priority",
    "Change the status of the task {task}",
    "I want to rename the task to {task}",
    "Set the task {task} as high priority",
    "Change the task {task} notes",
    "Update the description of the task {task}",
    "I need to modify the details of {task}",
    "Can you update {task} to be due {time}?",
    "Revise the task {task}",
    "Reschedule the task {task} to {time}",
    "Change the deadline for {task} to {time}",
    "The {task} deadline has changed to {time}",
    "Mark {task} as low priority",
    "Bump {task} up in priority",
    "Can I add notes to the task {task}?",
    "I want to add details to the task {task}",
    "Reschedule {task} for {time}",
    "Push {task} back to {time}",
    "Amend the task {task}",
    "Mark the task {task} as urgent",
]

# ── DELETE_TASK (52 templates) ────────────────────────────────────────────────
DELETE_TASK = [
    "{polite} delete the task {task}",
    "I need to remove the task {task}",
    "Can you delete my task to {task}?",
    "Remove {task} from my list",
    "I want to delete the task {task}",
    "The task {task} needs to be removed",
    "Take the task {task} off my list",
    "I'd like to delete the to-do {task}",
    "Delete task {task}",
    "Remove task: {task}",
    "Delete: {task}",
    "Remove from to-do: {task}",
    "Bin the task {task}",
    "Scrap the task {task}",
    "Drop the task {task}",
    "Nix the task {task}",
    "Get rid of the task {task}",
    "Chuck the task {task}",
    "Ditch the task {task}",
    "Kill the task {task}",
    "Forget the task {task}",
    "Never mind the task {task}",
    "Can you remove the task {task}?",
    "Could you delete this task {task}?",
    "Would you take {task} off my list?",
    "I don't need to {task} anymore",
    "The task {task} is no longer needed",
    "The task {task} is obsolete, remove it",
    "Strike {task} off my list",
    "Take {task} off my action items",
    "Clear {task} from my list",
    "I've decided not to {task}",
    "Cancel the task {task}",
    "Wipe {task} from my to-do list",
    "I want to remove {task} from my tasks",
    "Delete that task: {task}",
    "Purge {task} from my tasks",
    "Remove the {task} task please",
    "I'm not doing {task} anymore",
    "Take {task} out of my to-do list",
    "I've decided against {task}, remove it",
    "Get {task} off my list",
    "Lose the task {task}",
    "Discard the task {task}",
    "Erase the task {task} from my list",
    "That task is no longer relevant: {task}",
    "I want to cancel the task {task}",
    "Please delete the task {task}",
    "Could you remove {task} from my to-do list?",
    "Get rid of that {task} task",
    "The task {task} is done, remove it",
    "Remove that task: {task}",
]

# ── COMPLETE_TASK (77 templates) ──────────────────────────────────────────────
# NOTE: All broken {complete}d patterns replaced with {past_complete} or fixed phrasing
COMPLETE_TASK = [
    "{polite} mark the task {task} as done",
    "{polite} mark the task {task} as complete",
    "{polite} mark the task {task} as finished",
    "Mark my task {task} as done",
    "Mark my task {task} as complete",
    "Mark my task {task} as finished",
    "Mark {task} as done",
    "Mark {task} as complete",
    "Mark {task} as finished",
    "Can you mark {task} as done?",
    "Can you mark {task} as complete?",
    "Could you tick off the task {task}?",
    "Would you mark {task} done?",
    "Can I mark {task} as complete?",
    "Can you mark {task} as done for me?",
    "Please mark {task} as done",
    "{complete} task {task}",
    "{complete} the task {task}",
    "I want to {complete} the task {task}",
    "Can you {complete} the task {task}?",
    "Tick off: {task}",
    "Tick off the task {task}",
    "Cross off the task {task}",
    "I can tick off {task} now",
    "Close out {task}",
    "Flag {task} as complete",
    "Log {task} as done",
    "Set {task} to done",
    "Set {task} to complete",
    "I've done the task {task}",
    "I've {past_complete} the task {task}",
    "I've {past_complete} {task}",
    "I {past_complete} the task {task}",
    "I {past_complete} {task}",
    "I've just {past_complete} {task}",
    "Just {past_complete} {task}",
    "Finally {past_complete} {task}",
    "I finished {task}",
    "I've wrapped up {task}",
    "I've sorted {task}",
    "Wrapped up {task}",
    "The task {task} has been completed",
    "The task {task} is done",
    "The task {task} is complete",
    "The task {task} is finished",
    "{task} is done",
    "{task} is complete",
    "{task} is finished",
    "{task} has been done",
    "Task {task} done",
    "Mark done: {task}",
    "{task} - done",
    "{task} - complete",
    "Done: {task}",
    "Finished: {task}",
    "Completed: {task}",
    "Done with {task}",
    "That {task} is done",
    "Sorted the task {task}",
    "That's {task} sorted",
    "All done with {task}",
    "Knocked {task} off",
    "Smashed that task {task}",
    "Got {task} done",
    "I've got {task} done",
    "Right, {task} is done",
    "That task is sorted: {task}",
    "I managed to {task}",
    "I've ticked off {task}",
    "Can you complete {task}?",
    "I've {past_complete} that - {task}",
    "Just to let you know, {task} is done",
    "Update: {task} is complete",
    "Marking off {task}",
    "Task complete: {task}",
    "I can cross off {task}",
]

# ── QUERY_TASK (84 templates) ─────────────────────────────────────────────────
QUERY_TASK = [
    # Bare / no-slot templates (critical for fixing the reported failure)
    "what tasks do I have",
    "What tasks do I have due?",
    "What do I have due?",
    "What's due?",
    "What tasks are coming up?",
    "Show me my tasks",
    "Give me my tasks",
    "List my tasks",
    "What am I supposed to be doing?",
    "What's on my plate?",
    "What've I got to do?",
    "What tasks haven't I finished?",
    "Any overdue tasks?",
    "What's still pending?",
    "What tasks are incomplete?",
    "What tasks are complete?",
    "What tasks are in progress?",
    "What are the tasks with the highest priority?",
    "What tasks are pending?",
    "What's still to do?",
    "What haven't I completed yet?",
    "What tasks are left?",
    "What's on my to-do list?",
    "What do I need to do?",
    "What's remaining on my list?",
    "Any tasks I haven't done yet?",
    "What are my outstanding tasks?",
    "What are my open tasks?",
    "What are my pending tasks?",
    "What's my task list looking like?",
    "How many tasks do I have?",
    "What's my most urgent task?",
    "What tasks are overdue?",
    "What high priority tasks do I have?",
    "What's my next task?",
    "Any tasks I'm behind on?",
    "What needs doing?",
    "What haven't I done yet?",
    "What's left to do?",
    "What do I have left to do?",
    "Have I got any tasks outstanding?",
    "What's on my list?",
    "Anything I need to get done?",
    "What tasks am I working on?",
    "Have I got any unfinished tasks?",
    "What work have I got left?",
    "What's in my backlog?",
    "What am I behind on?",
    "What have I not finished yet?",
    "Have I got any actions outstanding?",
    # Templates with {time}
    "What tasks do I have {time}?",
    "Show me my tasks for {time}",
    "What's on my to-do list {time}?",
    "What tasks are due {time}?",
    "What tasks are due within the next {time}?",
    "Do I have any tasks {time}?",
    "What do I need to do on {time}?",
    "Can you show me my to-do list {time}?",
    "Show tasks for {time}",
    "List tasks due {time}",
    "My tasks {time}",
    "To-do list for {time}",
    "Tasks due {time}",
    "Pending tasks for {time}",
    "Outstanding tasks {time}",
    "Open tasks for {time}",
    "How many tasks do I have {time}?",
    "What's the next task due {time}?",
    "What are my tasks for {time}?",
    "What's my most urgent task {time}?",
    "What tasks are overdue {time}?",
    "Any high priority tasks {time}?",
    "What's due {time}?",
    "Do I have any tasks due {time}?",
    "Are there any pending tasks {time}?",
    "Have I got any tasks left {time}?",
    "What needs doing {time}?",
    "What haven't I done yet {time}?",
    "What've I got on my list {time}?",
    "What's left to do {time}?",
    "Give me my to-do list for {time}",
    "What tasks are coming up {time}?",
    "What am I supposed to be doing {time}?",
    "What's still pending {time}?",
]

# ── SET_REMINDER (75 templates) ───────────────────────────────────────────────
SET_REMINDER = [
    "Remind me {offset} the {event}",
    "Set a reminder for {offset} before {event}",
    "I need a reminder {offset} the {event}",
    "Can you remind me about the {event}?",
    "Create a reminder for {time} about {event}",
    "I want a reminder for the {event}",
    "Set up a notification {offset} the {event}",
    "Remind me to {task}",
    "Reminder: {task} at {time}",
    "Remind me: {task}",
    "Set reminder {offset} for {event}",
    "Alert {offset} {event}",
    "Notify me {offset} about {event}",
    "Ping me {offset} for {event}",
    "Nudge me {offset} about {event}",
    "Remind me at {time} about {event}",
    "Set a reminder for {time} to {task}",
    "Notification at {time} for {event}",
    "Alert me at {time} about {event}",
    "Buzz me at {time} for {event}",
    "Remind me to {task} at {time}",
    "Don't let me forget to {task}",
    "Make sure I remember to {task}",
    "I need reminding to {task}",
    "Can you set a reminder for the {event}?",
    "Could you remind me {offset} about {event}?",
    "Give me a heads-up {offset} for {event}",
    "Drop me a reminder {offset} about {event}",
    "Send me a nudge {offset} for {event}",
    "Pop a reminder in for {time} about {event}",
    # Bare reminders — no offset or time
    "Remind me about {event}",
    "Set a reminder for the {event}",
    "I need a reminder for {event}",
    "Can you remind me about {event}?",
    "Could you set me a reminder for {event}?",
    "I want a reminder about {event}",
    "Set up a reminder for {event}",
    "Create a reminder for {event}",
    "Add a reminder for {event}",
    # Alarm patterns
    "Set an alarm for {time}",
    "Set an alarm for the {event}",
    "Alarm for {event}",
    "Alarm at {time}",
    "Set an alarm for {time} for {event}",
    "Set an alarm for {time} to {task}",
    "I need an alarm for {time}",
    "Can you set an alarm for {time}?",
    "Put an alarm on for {time}",
    "Set my alarm for {time}",
    # Recurring reminders
    "Set a daily reminder to {task}",
    "Set a weekly reminder for {event}",
    "Remind me every day to {task}",
    "Give me a daily reminder to {task}",
    "Set up a recurring reminder for {event}",
    # With explicit time
    "Remind me about {event} at {time}",
    "Set a reminder for {event} at {time}",
    "Remind me at {time} to {task}",
    "I need a reminder at {time} to {task}",
    "Can you remind me at {time} about {event}?",
    "Give me a heads-up at {time} about {event}",
    "Shoot me a reminder at {time} for {event}",
    "Drop a reminder at {time} for {event}",
    # More notification phrasing
    "Send me a reminder about {event}",
    "Can you send me a reminder to {task}?",
    "I need to be reminded about {event}",
    "Alert me about {event}",
    "Notify me about {event}",
    "Ping me about {event}",
    "Give me a reminder for {event}",
    "Can you alert me {offset} about {event}?",
    "Set up an alert for {event}",
    "I need an alert {offset} the {event}",
    "Stick a reminder on for {event}",
    "Can you ping me at {time} about {event}?",
    "I'll need a nudge for {event}",
]

# ── UPDATE_REMINDER (52 templates) ────────────────────────────────────────────
UPDATE_REMINDER = [
    "{polite} change the reminder for {event} to {offset}",
    "I need to update the reminder for {event}",
    "Can you move the reminder for {event} to {offset}?",
    "Change my reminder for {event} to {time}",
    "The reminder for {event} needs to be updated",
    "I want to adjust the reminder time for {event}",
    "Could you modify the reminder for {event}?",
    "Update the notification time for {event} to {offset}",
    "Change reminder for {event} to {offset}",
    "Move reminder for {event} to {time}",
    "Update reminder for {event}: {offset}",
    "Adjust reminder time for {event}",
    "Shift reminder for {event} to {offset}",
    "Reminder for {event} now {offset}",
    "Make the reminder for {event} earlier",
    "Push the reminder for {event} back",
    "Change the {event} reminder from {offset} to later",
    "Move the notification for {event} to {offset}",
    "Reschedule the reminder for {event}",
    "Can I change the reminder time for {event}?",
    "Could you update the notification for {event}?",
    "Is it possible to move the reminder for {event}?",
    "Would you adjust the alert time for {event}?",
    "Tweak the reminder for {event}",
    "Shift the notification for {event} a bit",
    "Bump the reminder for {event} to {offset}",
    "Amend the reminder time for {event}",
    "Sort out the reminder for {event} to be {offset}",
    "Change when I get reminded about {event}",
    "Update the {event} alert to {offset}",
    "Change my reminder for {event}",
    "I need to update the alert for {event}",
    "Make the reminder for {event} later",
    "Move my alert for {event} to {time}",
    "Update the notification for {event} to {offset}",
    "Change the reminder time for {event} to {time}",
    "I want to push the reminder for {event} to {offset}",
    "Edit the reminder for {event}",
    "Modify when I'm reminded about {event}",
    "Change the nudge for {event} to {offset}",
    "I want a later reminder for {event}",
    "I want an earlier reminder for {event}",
    "Adjust the notification timing for {event}",
    "Can you move the alert for {event} to {offset}?",
    "Please update my reminder for {event} to {time}",
    "Change the ping time for {event} to {offset}",
    "Update when I get pinged for {event}",
    "I'd like to be reminded {offset} instead for {event}",
    "Alter the alert for {event} to {offset}",
    "Set the reminder for {event} to {offset} instead",
    "Can I have the {event} reminder at {time} instead?",
    "Move the buzz for {event} to {time}",
]

# ── DELETE_REMINDER (52 templates) ────────────────────────────────────────────
DELETE_REMINDER = [
    "{polite} delete the reminder for {event}",
    "I need to remove the reminder for {event}",
    "Can you cancel the reminder for {event}?",
    "Remove the notification for the {event}",
    "I want to delete the alert for {event}",
    "The reminder for {event} needs to be removed",
    "Turn off the reminder for {event}",
    "Cancel my reminder for the {event}",
    "Delete reminder for {event}",
    "Remove reminder for {event}",
    "Cancel reminder for {event}",
    "Clear reminder for {event}",
    "No reminder needed for {event}",
    "Forget the reminder for {event}",
    "Scrap the reminder for {event}",
    "Kill the reminder for {event}",
    "Turn off notifications for the {event}",
    "Stop reminding me about the {event}",
    "Remove the alert for {event} at {time}",
    "Cancel the notification for {event}",
    "Don't remind me about the {event}",
    "Can you remove the reminder for {event}?",
    "Could you cancel the notification for {event}?",
    "Would you delete the alert for {event}?",
    "Can I turn off the reminder for {event}?",
    "Bin the reminder for {event}",
    "Chuck the notification for {event}",
    "Ditch the alert for {event}",
    "Get rid of the reminder for {event}",
    "Take off the reminder for {event}",
    "I don't need the reminder for {event} anymore",
    "Switch off the reminder for {event}",
    "Disable the notification for {event}",
    "Remove the alarm for {event}",
    "I don't want to be reminded about {event}",
    "Stop the alert for {event}",
    "Clear all reminders for {event}",
    "Delete the alarm for {event}",
    "Turn the notification off for {event}",
    "No more reminders for {event}",
    "Mute the reminder for {event}",
    "Disable the alert for {event}",
    "I no longer need reminding about {event}",
    "Can you delete the notification for {event}?",
    "Please switch off my reminder for {event}",
    "Clear the alarm for {event}",
    "Get rid of the alert for {event}",
    "I don't need reminding about {event} anymore",
    "Bin the alert for the {event}",
    "I want to turn off notifications for {event}",
    "Please remove the notification for {event}",
    "I'd like to cancel the alarm for {event}",
]

# ── SET_PREFERENCES (82 templates) ───────────────────────────────────────────
SET_PREFERENCES = [
    # Working hours
    "{polite} set my working hours to {hours}",
    "I want to set my preferences to {hours}",
    "Can you update my settings to {hours}?",
    "Change my available hours to {hours}",
    "Set my timezone to {timezone}",
    "I'd like to configure my calendar to {hours}",
    "Update my scheduling preferences to {hours}",
    "Can you adjust my default settings to {hours}?",
    "Set working hours: {hours}",
    "Update preferences to {hours}",
    "Configure settings: {hours}",
    "Change timezone to {timezone}",
    "Set availability: {hours}",
    "Working hours {hours}",
    "Preferences: {preference}",
    # Time blocking
    "Don't schedule anything {condition}",
    "I prefer no meetings {condition}",
    "Set {time} as focus time",
    "Block out {time} for lunch",
    "I don't work {condition}",
    "Mark {time} as unavailable",
    "Set my default meeting duration to {duration}",
    # Conversational
    "Can I change my working hours to {hours}?",
    "Could you update my availability to {hours}?",
    "Would you adjust my preferences to {hours}?",
    "Sort out my preferences to {hours}",
    "Tweak my settings to {hours}",
    # Leave / OOO
    "Add annual leave on {time}",
    "I'm on holiday {time}",
    "Set my status to out of office {time}",
    # Buffer preferences
    "Always give me {duration} between meetings",
    "Keep {duration} free between back-to-back meetings",
    "Add a {duration} buffer after every meeting",
    "I need at least {duration} between appointments",
    "Set a {duration} gap between all meetings",
    # Boundary / hard limits
    "Never book meetings before {time}",
    "Don't schedule anything after {time}",
    "Don't book anything before {time} in the morning",
    "Don't schedule meetings after {time}",
    "I only take meetings {condition}",
    "Block my calendar {condition}",
    "No calls {condition} please",
    # Soft / day preferences
    "I prefer mornings for meetings",
    "I do my best work in the morning",
    "I prefer not to have meetings on Fridays",
    "Keep my afternoons free for deep work",
    "I work better in the mornings",
    "I'd rather have meetings in the afternoon",
    "Keep my mornings free for focused work",
    "I prefer to have my calls earlier in the day",
    "Schedule meetings in the afternoon where possible",
    "I like to start my day with a quiet hour",
    # Lunch and breaks
    "I like to have a lunch break at {time}",
    "I'd like {duration} for lunch every day",
    "Make sure I have a proper lunch break",
    "Set my lunch break preference to {time}",
    "I need a break {condition}",
    # Focus / protected blocks
    "Reserve {time} every day for {preference}",
    "Reserve my mornings for {preference}",
    "Set aside {time} each day for {preference}",
    "Keep {time} blocked for {preference}",
    "Protect {time} for {preference}",
    "I'd like to block out {time} as protected time",
    "Set a daily {preference} block at {time}",
    "Reserve {duration} every afternoon for {preference}",
    "I want {duration} of focus time every morning",
    "Enable focus mode {condition}",
    # Duration / meeting defaults
    "Set a minimum meeting duration of {duration}",
    "Don't book meetings shorter than {duration}",
    "Update my {preference} to {hours}",
    "I'd prefer not to have meetings {condition}",
    "Turn off meeting scheduling {condition}",
    # Timezone
    "Switch my timezone to {timezone}",
    "Update my timezone to {timezone}",
    "I'm now based in {timezone}, please update my settings",
    # Working week
    "My working week is {hours}",
    "Set my preferred {preference} to {hours}",
    "Update my default {preference}",
    "I work {hours} and want my calendar to reflect that",
]


# ── MASTER MAP ────────────────────────────────────────────────────────────────
NEW_TEMPLATES = {
    "CREATE_EVENT": CREATE_EVENT,
    "UPDATE_EVENT": UPDATE_EVENT,
    "DELETE_EVENT": DELETE_EVENT,
    "QUERY_EVENT": QUERY_EVENT,
    "FIND_FREE_TIME": FIND_FREE_TIME,
    "SUGGEST_TIME": SUGGEST_TIME,
    "CHANGE_RECURRENCE": CHANGE_RECURRENCE,
    "CREATE_TASK": CREATE_TASK,
    "UPDATE_TASK": UPDATE_TASK,
    "DELETE_TASK": DELETE_TASK,
    "COMPLETE_TASK": COMPLETE_TASK,
    "QUERY_TASK": QUERY_TASK,
    "SET_REMINDER": SET_REMINDER,
    "UPDATE_REMINDER": UPDATE_REMINDER,
    "DELETE_REMINDER": DELETE_REMINDER,
    "SET_PREFERENCES": SET_PREFERENCES,
}

# ── APPLY REPLACEMENTS ────────────────────────────────────────────────────────
print(f"Reading {FILE_PATH}...")
with open(FILE_PATH, 'r') as f:
    content = f.read()

print(f"Original file: {len(content)} chars\n")
print("Applying template replacements:")

for intent_name, templates in NEW_TEMPLATES.items():
    content = replace_template_list(content, intent_name, templates)

print(f"\nUpdated file: {len(content)} chars")

with open(FILE_PATH, 'w') as f:
    f.write(content)

print("\nAll done! Summary:")
for intent, templates in NEW_TEMPLATES.items():
    print(f"  {intent}: {len(templates)} templates")
total = sum(len(v) for v in NEW_TEMPLATES.values())
print(f"\nTotal templates across all intents: {total}")
