import os
import json
import numpy as np
import torch
from datasets import load_dataset
import evaluate
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    DataCollatorWithPadding
)
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import warnings

# Filter warnings for cleaner output
warnings.filterwarnings('ignore')
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# ===============================================================
# 1. Configuration
# ===============================================================

class TrainingConfig:
    """Centralized Configuration for Intent Classification"""
    MODEL_NAME = "distilbert-base-uncased"
    MAX_LENGTH = 128  # Intent commands are usually short
    
    # Training Hyperparameters
    BATCH_SIZE = 32
    GRADIENT_ACCUMULATION_STEPS = 1
    EPOCHS = 5
    LEARNING_RATE = 2e-5
    WEIGHT_DECAY = 0.01
    WARMUP_STEPS = 500
    SAVE_STEPS = 500
    EVAL_STEPS = 100
    
    # Paths (Based on your previous generation scripts)
    # Ensure these match where you saved your generated files
    TRAIN_FILE = "./intent_data/intent_train.jsonl"
    VALIDATION_FILE = "./intent_validation/intent_validation_final.jsonl"
    TEST_FILE = "./intent_validation/intent_test_final.jsonl"
    LABEL_MAP_FILE = "./intent_data/label_map.json"

    OUTPUT_DIR = "./scheduler_intent_model"
    LOGGING_DIR = "./logs_intent"
    
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

config = TrainingConfig()

# ===============================================================
# 2. Data Processing
# ===============================================================

def load_label_map(path):
    """
    Load the simple label map generated by the dataset script.
    Format expected: {"INTENT_NAME": INT_ID, ...}
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"Label map not found at {path}. Run data generator first.")
        
    with open(path, "r") as f:
        label2id = json.load(f)
    
    # Create the inverse mapping
    id2label = {int(v): k for k, v in label2id.items()}
    
    return id2label, label2id

def preprocess_function(examples, tokenizer):
    """
    Tokenize the text and map labels.
    """
    # Tokenize the text
    tokenized_inputs = tokenizer(
        examples["text"],
        truncation=True,
        max_length=config.MAX_LENGTH,
        padding="max_length" # Pad to max length for consistent batching
    )
    
    # Ensure labels are integers (dataset usually handles this, but safety first)
    tokenized_inputs["labels"] = examples["label"]
    
    return tokenized_inputs

def compute_metrics(eval_pred):
    """
    Compute Accuracy, Precision, Recall, and F1.
    """
    predictions, labels = eval_pred
    # Convert logits to class IDs
    predictions = np.argmax(predictions, axis=1)
    
    # Calculate simple accuracy
    accuracy = accuracy_score(labels, predictions)
    
    # Calculate precision, recall, f1 (weighted handles class imbalance)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average='weighted', zero_division=0
    )
    
    return {
        "accuracy": accuracy,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

# ===============================================================
# 3. Main Training Execution
# ===============================================================

def main():
    print("=" * 60)
    print("🚀 DistilBERT Intent Classification Training")
    print("=" * 60)
    print(f"Device detected: {config.DEVICE}")

    # Set seed
    torch.manual_seed(42)
    np.random.seed(42)

    # 1. Load Label Map
    print(f"\n📂 Loading label map from {config.LABEL_MAP_FILE}...")
    id2label, label2id = load_label_map(config.LABEL_MAP_FILE)
    num_labels = len(id2label)
    print(f"   Found {num_labels} intents: {list(label2id.keys())}")

    # 2. Load Datasets
    print("\n📂 Loading datasets...")
    data_files = {}
    
    if os.path.exists(config.TRAIN_FILE):
        data_files["train"] = config.TRAIN_FILE
    else:
        raise FileNotFoundError(f"Missing training file: {config.TRAIN_FILE}")
        
    if os.path.exists(config.VALIDATION_FILE):
        data_files["validation"] = config.VALIDATION_FILE
        print("   Found separate validation file (High quality).")
    else:
        print("   Warning: Separate validation file not found.")

    if os.path.exists(config.TEST_FILE):
        data_files["test"] = config.TEST_FILE
        print("   Found separate test file.")

    raw_datasets = load_dataset("json", data_files=data_files)

    # 3. Initialize Tokenizer & Model
    print("\n🤖 Initializing Model & Tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(config.MODEL_NAME)
    
    model = AutoModelForSequenceClassification.from_pretrained(
        config.MODEL_NAME,
        num_labels=num_labels,
        id2label=id2label,
        label2id=label2id,
        problem_type="single_label_classification"
    )
    model.to(config.DEVICE)

    # 4. Tokenize Datasets
    print("   Tokenizing data...")
    tokenized_datasets = raw_datasets.map(
        lambda x: preprocess_function(x, tokenizer),
        batched=True,
        remove_columns=["text", "label_name"] # Keep 'label' column, remove others
    )

    # 5. Training Arguments
    training_args = TrainingArguments(
        output_dir=config.OUTPUT_DIR,
        eval_strategy="steps",
        eval_steps=config.EVAL_STEPS,
        save_strategy="steps",
        save_steps=config.SAVE_STEPS,
        learning_rate=config.LEARNING_RATE,
        per_device_train_batch_size=config.BATCH_SIZE,
        per_device_eval_batch_size=config.BATCH_SIZE,
        num_train_epochs=config.EPOCHS,
        weight_decay=config.WEIGHT_DECAY,
        warmup_steps=config.WARMUP_STEPS,
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        logging_dir=config.LOGGING_DIR,
        logging_steps=50,
        report_to="none",
        fp16=(config.DEVICE == "cuda"),
        save_total_limit=2
    )

    # 6. Initialize Trainer
    # DataCollatorWithPadding is efficient for sequence classification
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets.get("validation"),
        processing_class=tokenizer, # Replaces tokenizer in newer transformers versions
        data_collator=data_collator,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
    )

    # 7. Train
    print("\n🔥 Starting Training...")
    train_result = trainer.train()

    # 8. Save Model
    print(f"\n💾 Saving model to {config.OUTPUT_DIR}...")
    trainer.save_model()
    # Save label map alongside model for easy inference loading later
    with open(os.path.join(config.OUTPUT_DIR, "label_map.json"), "w") as f:
        json.dump(label2id, f, indent=2)

    # 9. Evaluate on Test Set
    if "test" in tokenized_datasets:
        print("\n📊 Evaluating on Test Set...")
        test_results = trainer.evaluate(eval_dataset=tokenized_datasets["test"])
        
        print("\n" + "-"*30)
        print("TEST SET RESULTS")
        print("-" * 30)
        print(f"Accuracy:  {test_results['eval_accuracy']:.4f}")
        print(f"F1 Score:  {test_results['eval_f1']:.4f}")
        print(f"Precision: {test_results['eval_precision']:.4f}")
        print(f"Recall:    {test_results['eval_recall']:.4f}")
        print("-" * 30)

        # Save metrics
        with open(os.path.join(config.OUTPUT_DIR, "test_metrics.json"), "w") as f:
            json.dump(test_results, f, indent=2)

    # 10. Quick Inference Demo
    print("\n🔮 Quick Inference Demo")
    print("-" * 30)
    
    demo_texts = [
        "Can you schedule a meeting with the board for next Tuesday?",
        "Cancel my haircut appointment please.",
        "Add Sarah to the project sync.",
        "What time is my physics exam?",
        "Play some jazz music."
    ]
    
    # Put model in eval mode
    model.eval()
    
    for text in demo_texts:
        inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=config.MAX_LENGTH).to(config.DEVICE)
        with torch.no_grad():
            outputs = model(**inputs)
        
        # Get probabilities
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
        pred_id = torch.argmax(probs, dim=-1).item()
        confidence = probs[0][pred_id].item()
        pred_label = id2label[pred_id]
        
        print(f"Input: '{text}'")
        print(f"Pred:  {pred_label} ({confidence:.2%})")
        print("")

    print(f"\n✅ Done! Model saved to {config.OUTPUT_DIR}")

if __name__ == "__main__":
    main()