# ===============================================================
# modernbert_intent_trainer.py
# Optimised for ModernBERT Multi-Label Sequence Classification
#
# Requirements:
# pip install torch transformers datasets evaluate scikit-learn
# ===============================================================

import json
import torch
import numpy as np
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)
from sklearn.metrics import f1_score, precision_score, recall_score

# --- CONFIGURATION ---
MODEL_ID = "answerdotai/ModernBERT-base"
DATA_DIR = "./modernbert_data"
OUTPUT_DIR = "./modernbert_intent_modelv2"

MAX_LENGTH = 128
BATCH_SIZE = 32
LEARNING_RATE = 2e-5
NUM_EPOCHS = 4

def load_label_maps():
    """Load the label mappings generated by the dataset script."""
    with open(f"{DATA_DIR}/intent_label_map.json", "r") as f:
        label2id = json.load(f)
    with open(f"{DATA_DIR}/id_to_label.json", "r") as f:
        id2label = json.load(f)
    
    # Ensure keys are integers for id2label
    id2label = {int(k): v for k, v in id2label.items()}
    return label2id, id2label

def compute_metrics(eval_pred):
    """Calculate multi-label metrics using a 0.5 probability threshold."""
    logits, labels = eval_pred
    
    # Apply sigmoid to convert logits to probabilities
    probs = 1.0 / (1.0 + np.exp(-logits))
    
    # Threshold probabilities at 0.5 to get binary predictions
    predictions = (probs > 0.5).astype(int)
    
    # Calculate metrics
    f1_macro = f1_score(labels, predictions, average="macro", zero_division=0)
    f1_micro = f1_score(labels, predictions, average="micro", zero_division=0)
    precision_macro = precision_score(labels, predictions, average="macro", zero_division=0)
    recall_macro = recall_score(labels, predictions, average="macro", zero_division=0)
    
    return {
        "f1_macro": f1_macro,
        "f1_micro": f1_micro,
        "precision_macro": precision_macro,
        "recall_macro": recall_macro
    }

def main():
    print("Initialising ModernBERT Multi-Label Intent Training")
    
    label2id, id2label = load_label_maps()
    num_labels = len(label2id)
    
    print(f"Loading datasets from {DATA_DIR}...")
    dataset = load_dataset(
        "json",
        data_files={
            "train": f"{DATA_DIR}/multilabel_intent_train.jsonl",
            "validation": f"{DATA_DIR}/multilabel_intent_validation.jsonl", # Used during training epochs
            "strict_test": f"{DATA_DIR}/multilabel_intent_strict_validation.jsonl" # Used ONLY at the very end
        }
    )
    
    print(f"Loading tokenizer {MODEL_ID}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    
    def preprocess_function(examples):
        # Tokenize the text
        batch = tokenizer(
            examples["text"],
            padding=False, # We use a data collator for dynamic padding
            truncation=True,
            max_length=MAX_LENGTH
        )
        # Ensure labels are float32 for BCEWithLogitsLoss
        batch["labels"] = [
            [float(l) for l in label_list] for label_list in examples["labels"]
        ]
        return batch

    print("Tokenizing dataset...")
    tokenized_datasets = dataset.map(
        preprocess_function,
        batched=True,
        remove_columns=["text", "intent", "label_id"] # Remove original string columns
    )
    
    print(f"Loading model {MODEL_ID}...")
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_ID,
        num_labels=num_labels,
        problem_type="multi_label_classification",
        id2label=id2label,
        label2id=label2id
    )
    
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
    
    training_args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        learning_rate=LEARNING_RATE,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=NUM_EPOCHS,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1_macro",
        push_to_hub=False,
        fp16=torch.cuda.is_available(), # Use mixed precision if GPU is available
        logging_dir="./logs",
        logging_steps=50,
    )
    
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets["validation"], # Evaluates on standard validation during epochs
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )
    
    print("Starting training process...")
    trainer.train()
    
    print("Training complete. Commencing strict holdout evaluation...")
    # Evaluate strictly on the unseen templates
    strict_results = trainer.evaluate(tokenized_datasets["strict_test"])  # type: ignore
    
    print("\nFinal Strict Test Results:")
    for key, value in strict_results.items():
        print(f"  {key}: {value:.4f}")
    
    print(f"\nSaving final model to {OUTPUT_DIR}...")
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)

    # Save training logs to a text file
    log_path = f"{OUTPUT_DIR}/training_log.txt"
    with open(log_path, "w") as f:
        f.write("=== ModernBERT Intent Training Log ===\n\n")
        f.write("--- Training History ---\n")
        for entry in trainer.state.log_history:
            f.write(str(entry) + "\n")
        f.write("\n--- Final Strict Test Results ---\n")
        for key, value in strict_results.items():
            f.write(f"  {key}: {value:.4f}\n")
    print(f"Training log saved to {log_path}")

    print("Process finished successfully.")

if __name__ == "__main__":
    main()